# Netlify.toml dosyası
# Bu dosya, Netlify'ın Flutter projenizi doğru şekilde derlemesini ve yayımlamasını sağlar.
# GitHub'da projenizin ana dizininde (pubspec.yaml'nin olduğu yerde) bu dosyayı oluşturun.

[build]
  # Netlify'ın web derlemesi için çalıştıracağı komut
  command = "flutter build web --release"

  # Netlify'ın yayımlayacağı klasör
  publish = "build/web"

