# pubspec.yaml dosyası
# Bu dosya, projenin temel ayarlarını ve kullanacağımız tüm paketleri tanımlar.
# GitHub'da bu dosyayı oluşturup aşağıdaki içeriği yapıştırın.

name: unutmam_ben
description: Unutkanlık sorunu yaşayanlar için evrensel bir hatırlatıcı ve asistan uygulaması.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Veri saklama ve modeller için
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Bildirimler için
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  # Ses kayıt ve oynatma için
  record: ^5.0.4
  just_audio: ^0.9.38

  # Metinden Sese (TTS) için
  flutter_tts: ^4.1.0

  # Emoji klavyesi için
  emoji_picker_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
